### ISSUE TITLE
k8s_statefulsets health check does not work correctly

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-peer-discovery-k8s#11]
If a node comes up and cannot join the cluster it still reports healthy in K8s.  It should report as unhealthy.

command: ["rabbitmqctl", "status"]

does not seem to be the best way to detect node health in a cluster.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Peer discovery plugins have their own health check mechanisms if applicable, e.g. Consul and etcd do. [Cluster formation guide](http://www.rabbitmq.com/cluster-formation.html) explains how nodes with failing checks can be forcefully removed from the cluster.

There is a separate `rabbitmqctl` command that does a node-local health check but that’s not how it is supposed to be done either way.

We cannot help you with the amount of information provided.

**Comment by michaelklishin** [comment]
A quick grep suggests this plugin (or rabbitmq-autocluster, its predecessor) does not have a health check mechanism similar to their Consul or etcd counterparts. If Kubernetes has an alternative, that’s what should be added instead. Please start a mailing list discussion around what Kubernetes API endpoints may be suitable for that and what kind of parameters may need to be configured. Hopefull from that discussion we can collect a clear enough understanding to file a specific issue for this plugin (and possibly rabbitmq-autocluster for 3.6.x).
