### ISSUE TITLE
containers not initializing when using hostname instead of IP

### ISSUE THREAD

**Issue by artooro** [rabbitmq/rabbitmq-peer-discovery-k8s#18]
I'm not sure how others are doing it, but all the examples I've seen are to use `rabbit@$(MY_POD_IP)` for `RABBITMQ_NODENAME` but the issue I came across is if all the pods are rebooted at the same time all data is lost as well because the database dir ends up being `/var/lib/rabbitmq/mnesia/rabbit@10.1.2.3` and the IP address changes every time the POD is restarted.

So I strayed from the examples and used `rabbit@$(MY_POD_NAME)` instead in which case the database dir ends up as `/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-0` which is awesome.

I changed the configmap to:
```
cluster_formation.k8s.hostname_suffix = rabbitmq.default.svc.cluster.local
cluster_formation.k8s.address_type = hostname
```

But now the containers don't start fully, no cluster is created, and the last error in the log is:

`[warning] <0.32.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 100 messages/sec`

Which doesn't help a whole lot.

How is anyone getting data persistence when using this peer discovery plugin?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
> [warning] <0.32.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 100 messages/sec

is adressed by https://github.com/rabbitmq/rabbitmq-server/issues/1471. This plugin is not meant to solve every potential clustering automation problem and this is not a support forum.
