### ISSUE TITLE
About auto AUTOCLUSTER_CLEANUP

### ISSUE THREAD

**Issue by 82398485** [rabbitmq/rabbitmq-peer-discovery-k8s#31]
Hello, my idol @michaelklishin 
I have already used autocluster-0.8.0 at 3.6x , peer-discovery-k8s  at 3.7.x  in k8s.

Usually we use rabbitmq with some volume to store the mnesia(message/user/virtul hosts).  When all of nodes down, the volume  also have the information. So we can recover from it.

But when some one down for a long time, the other nodes will clear the node information from the cluster. When it up,  the information in the  volume  say "you should join the cluster", but the cluster will disagree...So the node can not be up.

I have already find one way to slove the problem, delete the volume . But it's not auto.
I tried to set AUTOCLUSTER_CLEANUP=false, but sometime also partition... It's so dangerous, so i give it up.

Could you give me some suggestion?   I'm puzzled for this problem for a long time.
Thanks.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
See server logs. This sounds like a textbook example of [the well known and documented downside](http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup) of automatic node cleanup.

**Comment by 82398485** [comment]
Thanks.  ^_^

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/CvSO2bSy_dU)
