### ISSUE TITLE
Queue Mirrorring

### ISSUE THREAD

**Issue by consult-kk** [rabbitmq/rabbitmq-peer-discovery-k8s#32]
Hi,
This plugin is great. But to achieve HA , how would I go about setting up mirrorring policy on all queues. Mirroring improves the availability , but at a cost of performance. In many systems message loss cannot be tolerated and mirroring solves the problem.
Can you provide any insight on how to automatically enable mirroring even when pods restart or are scaled.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin has nothing to do with mirroring.
