### ISSUE TITLE
kubernetes-peer discovery using hostname/nodename

### ISSUE THREAD

**Issue by kk-manh** [rabbitmq/rabbitmq-peer-discovery-k8s#35]
Hi,
Can you provide an example using the hostname rather than IP address. 
Using an IP address in a fluid environment like K8S where pods can be killed / spun up any number of times with different IP addresses, using IPs are inherently bad.
Especially when you need backup/restore from persistnt volumes and you end up with a bunch if folders in the mnesia folder that all have old / stale IP addresses.

**Comment by lukebakken** [comment]
Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

I see the following [`rabbitmq-users` message](https://groups.google.com/d/msg/rabbitmq-users/zh-c-R2Pch0/kk26FpJZEgAJ). Please post this question as a *new* discussion on the mailing list.

Thanks!

**Comment by kk-manh** [comment]
This is an issue. because the rabbitmq server and the peer discovery mechanism fails when the HOSTNAME is used for the clustering mechanism.

**Comment by lukebakken** [comment]
@kk-manh - you're asking for an example, which isn't considered to be an issue by the RabbitMQ team. We're happy to follow up on the mailing list. If we determine this to be an issue or _new feature_ worth further investigation, a GitHub issue will be created at that time.

Did you read [the documentation](https://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s)? Specifically, this section that mentions the use of hostnames:

> When a list of peer nodes is computed from a list of pod containers returned by Kubernetes, either  **hostnames** or IP addresses can be used. This is configurable using the cluster_formation.k8s.address_type key:

**Comment by rrakesh100** [comment]
This seems to be an issue.

https://groups.google.com/forum/#!topic/rabbitmq-users/g-g8lmWcn7Q

**Comment by daudn** [comment]
Did anyone find a solution for this?

**Comment by lukebakken** [comment]
@daudn - Please either see [the examples](https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/tree/master/examples/k8s_statefulsets) or ask a question on the mailing list.
