### ISSUE TITLE
Can rabbitmq-peer-discovery-k8s discover the service through SERVICE and automatically create a cluster?

### ISSUE THREAD

**Issue by prodanlabs** [rabbitmq/rabbitmq-peer-discovery-k8s#36]
I noticed that the automatic creation of the cluster was done by discovering the pod IP.
`rabbitmq.conf`
> cluster_formation.k8s.address_type = ip

`StatefulSet`
> - name: RABBITMQ_NODENAME
> value: "rabbit@$(MY_POD_IP)"

The IP of the pod after re-creation is variable，this means that the cluster nodes are also changing.

 `rabbitmq-autocluster` can discover services through SERVICE Name
E.g
>         - name: K8S_SERVICE_NAME
>           value: "rabbitmq"
>         - name: RABBITMQ_NODENAME
>           value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME)"

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Please consult [the docs](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s), which say: «When a list of peer nodes is computed from a list of pod containers returned by Kubernetes, either hostnames or IP addresses can be used…»
