### ISSUE TITLE
Dead rabbitMQ pod stays as "node not connected" and it loses the persistent messages.

### ISSUE THREAD

**Issue by arielb135** [rabbitmq/rabbitmq-peer-discovery-k8s#39]
Hello, i've created a 5 node cluster of rabbitMQ - and created a persistent queue, sent them a persistent message.
I've then killed the node, another one was created (of course, different IP) - but the old node (which is dead) is considered as not connected + i guess i cannot recover data there.
![image](https://user-images.githubusercontent.com/33662254/47138935-53bab200-d2c3-11e8-96af-7ccdd2c1d453.png)

![image](https://user-images.githubusercontent.com/33662254/47138955-5ae1c000-d2c3-11e8-9dc7-d9061c76a6d1.png)

I haven't seen in documentation what to do in those cases, Please assist?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin only covers peer discovery and [advertises as much](https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s#rabbitmq-peer-discovery-kubernetes). It does not control how persistent volumes are used in your Kubernetes setup, whether [stateful sets are used](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s), where the data directory is stored and so on. All of those things are highly relevant when it comes to node recreation and recovery.

The only thing it does control that's not peer discovery is [whether nodes no longer known to Kubernetes are forcefully removed](http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup) from the cluster.

You haven't provided any information about your deployment, no logs, no steps to reproduce. Please be respectful of the time of others and post all the relevant information to the list.

**Comment by michaelklishin** [comment]
The 3rd paragraph in the [Kubernetes peer discovery docs](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s) says:

```
It is highly recommended that RabbitMQ clusters are deployed using a stateful set.
If a stateless set is used recreated nodes will not have their persisted data and
will start as blank nodes. This can lead to data loss…
```

With not a whole lot of information about the environment, let me venture a guess: you do not use stateful sets.

**Comment by sandeep-t2s** [comment]
Did you get any solution for this?

**Comment by michaelklishin** [comment]
@sandeep-t2s this is not a support forum, as a comment above explains. Please collect logs from all nodes and start a mailing list thread. This plugin only covers peer discovery, how on disk data is stored/rearrached when nodes go down is entirely a matter of Kubernetes configuration and cannot be controlled by RabbitMQ or this plugin.

Instead of downvoting comments consider collecting data and using it to understand what is really going on in your system.
