### ISSUE TITLE
is there any rabbitmq operator in k8s

### ISSUE THREAD

**Issue by carolove** [rabbitmq/rabbitmq-peer-discovery-k8s#41]
hi,all
 i want to create rabbitmq stateful Set cluster in k8s by using k8s operator controller, is there any demo project?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This is an area of research at Pivotal at the moment, there's nothing to share at the moment.
