### ISSUE TITLE
RabbitMQ Pods are restarting on kubernetes

### ISSUE THREAD

**Issue by anoopswsib** [rabbitmq/rabbitmq-peer-discovery-k8s#46]
I have deployed rabbitmq on kubernetes 1.14 using helm chart ha. After few hours, the pods are restarting without any reason. The issue is exactly same as the one mentioned by another user : https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/issues/43

I am having same issues as the other person in that thread.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin is extremely unlikely to be a contributing factor to pod restarts. This is not a one-click Kubernetes solution, it's merely a peer discovery mechanism. Please start a mailing list thread.
